log_setup.py | [INFO] | 2022-03-12 23:41:46,893 | __main__ | : Log Setup Completed, called from weather_open gpd in log_setup:54
log_setup.py | [INFO] | 2022-03-12 23:42:56,721 | __main__ | : Log Setup Completed, called from weather_open gpd in log_setup:54
log_setup.py | [INFO] | 2022-03-12 23:46:44,483 | __main__ | : Log Setup Completed, called from weather_open gpd in log_setup:54
log_setup.py | [INFO] | 2022-03-12 23:47:55,776 | __main__ | : Log Setup Completed, called from weather_open gpd in log_setup:54
weather_open gpd.py | [INFO] | 2022-03-12 23:48:04,749 | __main__ | : Inizio in weather_open gpd:97
weather_open gpd.py | [INFO] | 2022-03-12 23:48:04,749 | __main__ | : name 'cities' is not defined in weather_open gpd:104
Traceback (most recent call last):
  File "c:/Users/forteg/OneDrive - Fratelli Carli Spa/Desktop/Python/Training/api_sample/weather_open gpd.py", line 101, in <module>
    main()
  File "c:/Users/forteg/OneDrive - Fratelli Carli Spa/Desktop/Python/Training/api_sample/weather_open gpd.py", line 52, in main
    for idx, city in cities.iterrows():
NameError: name 'cities' is not defined
weather_open gpd.py | [INFO] | 2022-03-12 23:48:04,757 | __main__ | : Fine in weather_open gpd:108
log_setup.py | [INFO] | 2022-03-12 23:48:32,420 | __main__ | : Log Setup Completed, called from weather_open gpd in log_setup:54
weather_open gpd.py | [INFO] | 2022-03-12 23:48:34,200 | __main__ | : Inizio in weather_open gpd:97
weather_open gpd.py | [INFO] | 2022-03-12 23:48:36,413 | __main__ | : Fine in weather_open gpd:108
log_setup.py | [INFO] | 2022-03-12 23:50:47,210 | __main__ | : Log Setup Completed, called from weather_open gpd in log_setup:54
weather_open gpd.py | [INFO] | 2022-03-12 23:50:48,842 | __main__ | : Inizio in weather_open gpd:97
weather_open gpd.py | [INFO] | 2022-03-12 23:50:50,993 | __main__ | : Fine in weather_open gpd:108
log_setup.py | [INFO] | 2022-03-12 23:51:26,358 | __main__ | : Log Setup Completed, called from weather_open gpd in log_setup:54
weather_open gpd.py | [INFO] | 2022-03-12 23:51:28,073 | __main__ | : Inizio in weather_open gpd:97
weather_open gpd.py | [INFO] | 2022-03-12 23:51:30,167 | __main__ | : Fine in weather_open gpd:108
log_setup.py | [INFO] | 2022-03-12 23:53:30,044 | __main__ | : Log Setup Completed, called from weather_open gpd in log_setup:54
weather_open gpd.py | [INFO] | 2022-03-12 23:58:04,637 | __main__ | : Inizio in weather_open gpd:92
weather_open gpd.py | [INFO] | 2022-03-12 23:58:18,723 | __main__ | : Fine in weather_open gpd:103
log_setup.py | [INFO] | 2022-03-12 23:58:26,973 | __main__ | : Log Setup Completed, called from weather_open gpd in log_setup:54
weather_open gpd.py | [INFO] | 2022-03-12 23:58:28,715 | __main__ | : Inizio in weather_open gpd:93
weather_open gpd.py | [INFO] | 2022-03-12 23:58:30,685 | __main__ | : Fine in weather_open gpd:104
log_setup.py | [INFO] | 2022-03-12 23:59:09,657 | __main__ | : Log Setup Completed, called from weather_open gpd in log_setup:54
weather_open gpd.py | [INFO] | 2022-03-12 23:59:11,596 | __main__ | : Inizio in weather_open gpd:93
weather_open gpd.py | [INFO] | 2022-03-12 23:59:13,526 | __main__ | : Fine in weather_open gpd:104
log_setup.py | [INFO] | 2022-03-13 00:00:32,799 | __main__ | : Log Setup Completed, called from weather_open gpd in log_setup:54
weather_open gpd.py | [INFO] | 2022-03-13 00:00:32,936 | __main__ | : Inizio in weather_open gpd:91
weather_open gpd.py | [INFO] | 2022-03-13 00:00:36,636 | __main__ | : Fine in weather_open gpd:102
